name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/7 * *"
  workflow_dispatch:
jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "Build AppImage"
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: "Build AppImage"
            arch: aarch64
    steps:
    - uses: actions/checkout@v4

    - name: Make AppImage
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar squashfs-tools zsync desktop-file-utils
        chmod +x ./*-appimage.sh
        ./*-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: AppImage-${{ matrix.arch }}
        path: 'dist'

    - name: Upload version file
      uses: actions/upload-artifact@v4.6.2
      with:
       name: version
       path: ~/version
       overwrite: true

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          name: AppImage-x86_64

      - uses: actions/download-artifact@v4.3.0
        with:
          name: AppImage-aarch64

      - uses: actions/download-artifact@v4.3.0
        with:
          name: version

      - name: Read version and Get date
        run: |
          echo "VERSION=$(cat version)" >> "${GITHUB_ENV}"
          echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Floorp: ${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}@${{ env.DATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*

      - uses: actions/checkout@v4
      - name: Update LATEST_VERSION
        run: |
          echo "${{ env.VERSION }}" > ./LATEST_VERSION
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./LATEST_VERSION
          git commit --allow-empty -m 'bump `LATEST_VERSION` [skip ci]'
          git push
